# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Fast API CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3

    - name: Deploy to Heroku
      env:
        HEROKU_API_TOKEN: ${{secrets.HEROKU_API_TOKEN}}
        HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}
      run: |
        git remote add heroku https://${{secrets.HEROKU_API_TOKEN}}@git.heroku.com/${{secrets.HEROKU_APP_NAME}}.git
        git push heroku HEAD:master -f
